### PR TITLE
Improved the program deployment procedure even further

### PR DESCRIPTION
**Pull request by antoninkriz**
- implemented the `deploy_all_programs` function
- ~~refactored the code to use the `utils` (`trdelnik-utils`) crate to get rid of some (potentially) duplicated code~~
- ~~removed the first keypair from `PROGRAM_KEYPAIRS` which somehow fails to find a program after deployment~~
  - ~~this might be just some mistake on my side and might need to be doublechecked~~

### CODE REVIEW

**Comment by tribuste** [comment]
_removed the first keypair from PROGRAM_KEYPAIRS which somehow fails to find a program after deployment
this might be just some mistake on my side and might need to be doublechecked_

Doublechecked and it's failing for me as well, not sure why but will investigate bit further what's the problem with this key, but for now we can remove it from keys

**Comment by tribuste** [comment]
`deploy_all_programs` looks good, but I'm not sure about `trdelnik-utils` crate, I don't think is really helpful to structure it like that. Let's talk about it on planning.

**Comment by vmarcin** [comment]
> _removed the first keypair from PROGRAM_KEYPAIRS which somehow fails to find a program after deployment this might be just some mistake on my side and might need to be doublechecked_
> 
> Doublechecked and it's failing for me as well, not sure why but will investigate bit further what's the problem with this key, but for now we can remove it from keys

No, we can't. The order of keypairs will be wrong after the removal. You will pass 0 to a `program_keypair()` function and according to the documentation, you should get a keypair starting with `Poo...`, however you will get the one starting with `Po1`

**Comment by tribuste** [comment]
Good catch, so we have to change documentation to match the implementation, I think that's OK for now

**Comment by antoninkriz** [comment]
I cleaned up this PR to contain only the stuff related to `deploy_all_programs`.
I got rid of the refactoring with the `utils` crate and the workaround the error with `program_keypair`.

**Comment by antoninkriz** [comment]
The pipeline is now failing for `Trdelnik tests / turnstile (pull_request)`, but I saw that there's some fix for it in the https://github.com/Ackee-Blockchain/trdelnik/pull/63 PR.
Should I wait for it to be merged or should I also implement a fix?

**Comment by stefanprokopdev** [comment]
> The pipeline is now failing for `Trdelnik tests / turnstile (pull_request)`, but I saw that there's some fix for it in the #63 PR. Should I wait for it to be merged or should I also implement a fix?

You can wait, I think it will be done today.

**Comment by antoninkriz** [comment]
Since we don’t know the program ID after build - when running tests - we aren’t able to use a correct `program_keypairs(n)` when deploying these programs since we don’t even know what program ID the program that’s being deployed even has. This might be solved by adding the program ID to the `Cargo.toml` inside `.program_client`, but we would need to parse it which adds even more overhead to a small function with a minor QOL improvement.
Closing.

**Comment by antoninkriz** [comment]
This https://github.com/coral-xyz/anchor/pull/868 PR in Anchor might make things much easier, sadly there's no progress being made since `2021-10-15`.

**Pull request closed without merging**
